# Generated by Django 5.2.7 on 2025-10-17 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la categoría')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='Identificador (slug)')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del beat')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio (CLP)')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Stock disponible')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del beat')),
                ('imagen', models.ImageField(upload_to='beats/', verbose_name='Carátula')),
                ('bpm', models.PositiveIntegerField(default=120, verbose_name='BPM')),
                ('key', models.CharField(blank=True, max_length=12, verbose_name='Key')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beats', to='store.categoria')),
            ],
            options={
                'verbose_name': 'Beat',
                'verbose_name_plural': 'Beats',
                'ordering': ['-creado_en'],
            },
        ),
    ]
